"""Regenerates LEADERBOARD.md from scratch by exhaustively searching all
9! mode orderings, for every baseline registered in baselines.BASELINES,
on the 3x3 grid (M=9) -- the one lattice size small enough to search
exactly rather than trust a single ordering.

Run this after adding or improving a baseline. LEADERBOARD.md is a
generated artifact -- never hand-edit it, since the whole point is that
every number in it is the literal output of running the current code,
not a claim. Takes a few minutes per registered baseline.
"""

import itertools
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from baselines import BASELINES
from harness.evaluate import evaluate
from harness.lattice import hamiltonian, rectangle

LX = LY = 3
M = LX * LY


def best_for(encode_fn):
    best_total = None
    best_max = None
    for perm in itertools.permutations(range(M)):
        spec = rectangle(LX, LY, ordering="custom", perm=list(perm))
        terms = hamiltonian(spec, model="full")
        result = evaluate(spec, encode_fn, terms)
        if not result["passed"]:
            raise RuntimeError(f"encode_fn failed verify() at perm {perm}: {result}")
        if best_total is None or result["total_weight"] < best_total[0]:
            best_total = (result["total_weight"], perm)
        if best_max is None or result["max_weight"] < best_max[0]:
            best_max = (result["max_weight"], perm)
    return best_total[0], best_max[0]


def main():
    rows = []
    for name, encode_fn in BASELINES.items():
        t0 = time.time()
        total, max_weight = best_for(encode_fn)
        print(f"{name}: total={total} max={max_weight} ({time.time() - t0:.0f}s)")
        rows.append((name, total, max_weight))

    rows.sort(key=lambda r: r[1])  # best total first

    leaderboard_path = Path(__file__).parent.parent / "LEADERBOARD.md"
    with open(leaderboard_path, "w") as f:
        f.write("# Leaderboard -- 3x3 grid (M=9)\n\n")
        f.write(
            "Generated by `scripts/update_leaderboard.py` — every number here is the\n"
            "true global optimum, found by exhaustive search over all `9!` mode\n"
            "orderings, not a claim. **Do not hand-edit this file** — run the script\n"
            "again after adding or improving a `baselines/` entry.\n\n"
        )
        f.write("| encoding | best total weight | best max weight |\n")
        f.write("|---|---|---|\n")
        for name, total, max_weight in rows:
            f.write(f"| {name} | {total} | {max_weight} |\n")

    print(f"wrote {leaderboard_path}")


if __name__ == "__main__":
    main()
